package com.reserve.mapper;

import java.util.List;
import java.util.Map;

import com.reserve.model.ReserveRecord;

public interface ReserveRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_record
     *
     * @mbggenerated Wed Dec 02 10:13:11 CST 2015
     */
    int insert(ReserveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_record
     *
     * @mbggenerated Wed Dec 02 10:13:11 CST 2015
     */
    int insertSelective(ReserveRecord record);
    
    List<ReserveRecord> selectSelective(Map<String, Object> param);
    
    int countSelectSelective(Map<String, Object> param);
}