package com.reserve.mapper;

import java.util.List;
import java.util.Map;

import com.reserve.model.ReserveRecord;

public interface ReserveRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_record
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    int insert(ReserveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reserve_record
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    int insertSelective(ReserveRecord record);
    
    ReserveRecord selectByPrimaryKey(Long id);
    
    List<ReserveRecord> selectSelective(Map<String, Object> param);
    
    int countSelectSelective(Map<String, Object> param);
    
    int deleteByPrimaryKey(Long id);
}