package com.reserve.model;

import java.text.SimpleDateFormat;
import java.util.Date;

public class ReserveRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_record.id
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_record.name
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_record.mobile
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_record.id_number
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_record.reserve_time
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    private Date reserveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_record.create_time
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_record.description
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_record.id_photo
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    private byte[] idPhoto;
    
    private boolean hasPhoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_record.id
     *
     * @return the value of reserve_record.id
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_record.id
     *
     * @param id the value for reserve_record.id
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_record.name
     *
     * @return the value of reserve_record.name
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_record.name
     *
     * @param name the value for reserve_record.name
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_record.mobile
     *
     * @return the value of reserve_record.mobile
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_record.mobile
     *
     * @param mobile the value for reserve_record.mobile
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_record.id_number
     *
     * @return the value of reserve_record.id_number
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_record.id_number
     *
     * @param idNumber the value for reserve_record.id_number
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_record.reserve_time
     *
     * @return the value of reserve_record.reserve_time
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public Date getReserveTime() {
        return reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_record.reserve_time
     *
     * @param reserveTime the value for reserve_record.reserve_time
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public void setReserveTime(Date reserveTime) {
        this.reserveTime = reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_record.create_time
     *
     * @return the value of reserve_record.create_time
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_record.create_time
     *
     * @param createTime the value for reserve_record.create_time
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_record.description
     *
     * @return the value of reserve_record.description
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_record.description
     *
     * @param description the value for reserve_record.description
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_record.id_photo
     *
     * @return the value of reserve_record.id_photo
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public byte[] getIdPhoto() {
        return idPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_record.id_photo
     *
     * @param idPhoto the value for reserve_record.id_photo
     *
     * @mbggenerated Thu Dec 03 21:17:18 CST 2015
     */
    public void setIdPhoto(byte[] idPhoto) {
        this.idPhoto = idPhoto;
    }

	public String getReserveTimeStr() {
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm");
		if (reserveTime != null) {
			return format.format(reserveTime);
		} else {
			return "";
		}
	}

	public void setReserveTimeStr(String reserveTimeStr) {
	}
	
	public String getCreateTimeStr() {
		SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm");
		if (createTime != null) {
			return format.format(createTime);
		} else {
			return "";
		}
	}

	public void setCreateTimeStr(String createTimeStr) {
	}

	public boolean getHasPhoto() {
		if (idPhoto != null && idPhoto.length >0) {
			return true;
		} else {
			return false;
		}
	}

	public void setHasPhoto(boolean hasPhoto) {
	}
    
}